// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOkw8s69VLb45mXwb3MsjJ4NiTmuOUvLQ',
    appId: '1:657934624182:web:bc5fe9b2e5b492ed8d8d17',
    messagingSenderId: '657934624182',
    projectId: 'children-tasks-dev',
    authDomain: 'children-tasks-dev.firebaseapp.com',
    storageBucket: 'children-tasks-dev.firebasestorage.app',
    measurementId: 'G-X435EBGLS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDW3ix84cW89c4_5gUG3zfus98Yb697MY',
    appId: '1:657934624182:android:09fa9b4075be588f8d8d17',
    messagingSenderId: '657934624182',
    projectId: 'children-tasks-dev',
    storageBucket: 'children-tasks-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUn6VSCywEr8It2mR8emcYDs57SYRarA',
    appId: '1:657934624182:ios:8a9551bd24d76f8a8d8d17',
    messagingSenderId: '657934624182',
    projectId: 'children-tasks-dev',
    storageBucket: 'children-tasks-dev.firebasestorage.app',
    iosBundleId: 'br.com.semogdev.childrentasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUn6VSCywEr8It2mR8emcYDs57SYRarA',
    appId: '1:657934624182:ios:8a9551bd24d76f8a8d8d17',
    messagingSenderId: '657934624182',
    projectId: 'children-tasks-dev',
    storageBucket: 'children-tasks-dev.firebasestorage.app',
    iosBundleId: 'br.com.semogdev.childrentasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkw8s69VLb45mXwb3MsjJ4NiTmuOUvLQ',
    appId: '1:657934624182:web:c4390335ad864ec28d8d17',
    messagingSenderId: '657934624182',
    projectId: 'children-tasks-dev',
    authDomain: 'children-tasks-dev.firebaseapp.com',
    storageBucket: 'children-tasks-dev.firebasestorage.app',
    measurementId: 'G-X3DK7669YW',
  );
}
