// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqOTX8m-UySkfxlA463X-NhU1TvePd5A',
    appId: '1:1048299264527:web:33898619a3a1e5e8eba17a',
    messagingSenderId: '1048299264527',
    projectId: 'children-tasks-prod',
    authDomain: 'children-tasks-prod.firebaseapp.com',
    storageBucket: 'children-tasks-prod.firebasestorage.app',
    measurementId: 'G-K3C0PBRN21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxJGIjBwgNeGUlcC_Xmnc8bJIogydxIg',
    appId: '1:1048299264527:android:a2aef20a1a4f7cf0eba17a',
    messagingSenderId: '1048299264527',
    projectId: 'children-tasks-prod',
    storageBucket: 'children-tasks-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcrotV6iqa9ViNeeP31RdmfqpSkxWpHI',
    appId: '1:1048299264527:ios:a90a7eee9d7c6aa0eba17a',
    messagingSenderId: '1048299264527',
    projectId: 'children-tasks-prod',
    storageBucket: 'children-tasks-prod.firebasestorage.app',
    iosBundleId: 'br.com.semogdev.childrentasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTcrotV6iqa9ViNeeP31RdmfqpSkxWpHI',
    appId: '1:1048299264527:ios:a90a7eee9d7c6aa0eba17a',
    messagingSenderId: '1048299264527',
    projectId: 'children-tasks-prod',
    storageBucket: 'children-tasks-prod.firebasestorage.app',
    iosBundleId: 'br.com.semogdev.childrentasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChqOTX8m-UySkfxlA463X-NhU1TvePd5A',
    appId: '1:1048299264527:web:a919fd541d7d4a37eba17a',
    messagingSenderId: '1048299264527',
    projectId: 'children-tasks-prod',
    authDomain: 'children-tasks-prod.firebaseapp.com',
    storageBucket: 'children-tasks-prod.firebasestorage.app',
    measurementId: 'G-H0JBP3JFWM',
  );
}
